spring.application.name=product-service
server.port=8082

eureka.client.service-url.default-zone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.client.healthcheck.enabled=true

eureka.instance.metadata-map.github.repo=alekrszp/microservice-java-2026

management.endpoints.web.exposure.include=health,info,metrics,circuit-breakers,circuit-breaker-events
management.endpoint.health.show-details=always
management.info.env.enabled=true
management.endpoint.health.probes.enabled=true
management.health.defaults.enabled=true

info.app.name=${spring.application.name}
info.app.description=Product Service
info.app.autor=Alessandro

spring.cloud.openfeign.client.config.default.connect-timeout=5000
spring.cloud.openfeign.client.config.default.read-timeout=5000

spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=100,expireAfterWrite=10m

resilience4j.circuitbreaker.instances.currencyClient.sliding-window-size=10
resilience4j.circuitbreaker.instances.currencyClient.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.currencyClient.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.currencyClient.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.currencyClient.automatic-transition-from-open-to-half-open-enabled=true

resilience4j.retry.instances.currencyClient.max-attempts=3
resilience4j.retry.instances.currencyClient.wait-duration=2s
resilience4j.retry.instances.currencyClient.enable-exponential-backoff=true
resilience4j.retry.instances.currencyClient.exponential-backoff-multiplier=2
resilience4j.retry.instances.currencyClient.enable-randomized-wait=true
resilience4j.retry.instances.currencyClient.randomized-wait-factor=0.5